services:
  laboutik_postgres:
    image: postgres:11.5-alpine
    restart: always
    env_file: .env
    container_name: laboutik_postgres
    hostname: laboutik_postgres
    volumes:
      - laboutik_postgres_data:/var/lib/postgresql/data
    networks:
      - laboutik_backend

  laboutik_memcached:
    image: memcached:1.6
    container_name: laboutik_memcached
    hostname: laboutik_memcached
    restart: always
    networks:
      - laboutik_backend

  laboutik_redis:
    image: redis:6-alpine
    restart: always
    env_file: .env
    container_name: laboutik_redis
    hostname: laboutik_redis
    networks:
      - laboutik_backend

  laboutik_django:
#    image: tibillet/laboutik:latest
    build: .
    restart: always
    env_file: .env
    container_name: laboutik_django
    hostname: laboutik_django
    volumes:
      - ./:/DjangoFiles
    links:
      - laboutik_postgres:postgres
      - laboutik_redis:redis
      - laboutik_memcached:memcached
    depends_on:
      - laboutik_postgres
      - laboutik_redis
      - laboutik_memcached
    networks:
      - laboutik_backend
    extra_hosts:
      - "fedow.tibillet.localhost:172.17.0.1"
      - "demo.tibillet.localhost:172.17.0.1"
      - "billetistan.tibillet.localhost:172.17.0.1"
      - "cashless.tibillet.localhost:172.17.0.1"
  #    command: "sleep infinity"
  #    command: "bash /home/tibillet/LaBoutik/DjangoFiles/launch_prod.sh"


  laboutik_celery:
#    image: tibillet/laboutik:latest
    build: .
    restart: always
    env_file: .env
    container_name: laboutik_celery
    hostname: laboutik_celery
    volumes:
      - ./:/DjangoFiles
    links:
      - laboutik_postgres:postgres
      - laboutik_redis:redis
      - laboutik_memcached:memcached
    depends_on:
      - laboutik_postgres
      - laboutik_django
      - laboutik_memcached
    networks:
      - laboutik_backend
    extra_hosts:
      - "fedow.tibillet.localhost:172.17.0.1"
      - "demo.tibillet.localhost:172.17.0.1"
      - "billetistan.tibillet.localhost:172.17.0.1"
      - "cashless.tibillet.localhost:172.17.0.1"
    command: "poetry run celery -A Cashless worker -l INFO"


  laboutik_nginx:
    image: nginx
    restart: always
    container_name: laboutik_nginx
    hostname: laboutik_nginx
    depends_on:
      - laboutik_django
    links:
      - laboutik_django:laboutik_django
    volumes:
      - ./www:/DjangoFiles/www
      - ./logs:/DjangoFiles/logs
      - ./nginx:/etc/nginx/conf.d
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.laboutik_nginx.tls.certresolver=myresolver
      - traefik.http.routers.laboutik_nginx.rule=Host(`${DOMAIN}`)
    networks:
      - frontend
      - laboutik_backend

networks:
  frontend:
    external: true
  laboutik_backend:

volumes:
  laboutik_postgres_data:


# Avant de build :
## Tradution :
### Mettre a jour le fichier de traduction : django-admin makemessages -l en && django-admin makemessages -l fr
### Changer les textes dans locale/en/django.po
### Compiler les traductions : django-admin compilemessages

# docker build -t laboutik . && docker tag laboutik tibillet/laboutik:latest && docker tag laboutik tibillet/laboutik:0.9.6 && docker push tibillet/laboutik:latest && docker push tibillet/laboutik:0.9.6

